### ISSUE TITLE
Even basic custom functions show only #BUSY on Excel

### ISSUE THREAD

**Issue by pasunmaa** [OfficeDev/script-lab#1052]
ScriptLab has recently updated After that custom functions stopped working. They only show #BUSY.
Microsoft announcement: https://devblogs.microsoft.com/microsoft365dev/update-on-the-future-of-the-script-lab-office-add-in/

Even most simple functions do not work. E.g.
/**
 * Doubles the number
 * @customfunction
 * @param {number} num
 * @returns the number
 */
function double(num) {

  return num *2;
}

### Bug Report

- **Host**: Excel for Mac, Version 16.83 (24031120) + Excel for Web
- **OS**: MacOS Sonoma, Version 14.4.1; node.js v20.12.1
- **Browser**: Chrome Version 123.0.6312.107 (Official Build) (x86_64)
- **Environment**: (fill out. eg: alpha, beta, prod)

#### Expected behavior:

Simple custom function would return the correct value from Javascript immediately.

#### Actual behavior:

I can see only #BUSY in the excel cell

#### Steps to Reproduce:

1. Register the function in ScriptLab
2. Call the function from excel cell
3. I tried to remove ScriptLab and reinstall it, but it looks like to be removed, but when I restart excel, it appears automatically back.

**Comment by wandyezj** [comment]
Hello @pasunmaa 

Thank you for reporting this issue.

We are working on a fix.

**Comment by wandyezj** [comment]
Hello @pasunmaa

I have deployed a fix.

To verify you have the latest update:

1. Open the _Edit taskpane_
1. Click `settings` (gear on lower right side)
1. Click `About`
1. Check that the Last Updated is `Mon, 09 Apr 2024`

**Comment by pasunmaa** [comment]
I'm seeing
Last Updated: 'Mon, 08 Apr 2024 20:30:06 GMT' 
Commit: Merged PR 2889339: Updates
Environment: CDN Production

and still getting #BUSY (on Excel for Mac). I tried to reload the plug-in from i > Reload menu.

**Comment by pasunmaa** [comment]
Hello @wandyezj,

I tried to remove the add-in completely and wish to reinstall from 'empty table'. I faced other issues:
<img width="737" alt="image" src="https://github.com/OfficeDev/script-lab/assets/23167594/832f713c-7a85-488a-b987-463276db0bfe">
Add-in further information and Rate and review links do not work: "This o15.officeredir.microsoft.com page can’t be found"

When I chose remove, it disappeared gracefully from the above windows. When I press close, the script lab menu disappears too, as expected. Then exit Excel. All fine, but when I restart with excel file containing custom functions it is back again.
