### ISSUE TITLE
Deleted snippet is still shown in the editor after a click on the hamburger menue

### ISSUE THREAD

**Issue by maninweb** [OfficeDev/script-lab#817]
Hi there,

I am running Script Lab 1.1.0 from the store in Excel Insider (10211.20004) in a Windows 10 VM. I noticed, that if I delete snippets, a click on the hamburger menue still shows the editor with the deleted snippet.
I did the following steps to reproduce the error.

I firstly cleaned up my Internet Explorer Cache for having nothing locally stored. I opened Script Lab, its code pane and created 3 blank snippets, which I named Blank snippet 1 ... 3. I added to each snippet just a comment in the code for differentiating them.

![image](https://user-images.githubusercontent.com/13045898/40277528-897a8100-5c20-11e8-8c5d-cd6fea82d201.png)

So, after that, I have in my collection.

![image](https://user-images.githubusercontent.com/13045898/40277533-a2d4f5d6-5c20-11e8-8862-a3669db84632.png)

Then I opened snippet nr. 2 and deleted it by using the trash icon in the header. The code pane then automatically switches to the overview of my snippets and snippet nr. 2 is gone.

![image](https://user-images.githubusercontent.com/13045898/40277562-03719b4c-5c21-11e8-80dd-e89c0a42fd82.png)

From this view, clicking now on the hamburger menue shows this:

![image](https://user-images.githubusercontent.com/13045898/40277567-253e2d94-5c21-11e8-8aca-f5c651795aff.png)

Interesting is too, that if I am in the view (shown above), it seems to be possible to restaure the snippet. It's not possible to click with the mouse, but pressing the tab key lets me reach the editor, which then becomes editable and as soon I type something, the script is restored/stored.

It is also possible to reproduce this with the other snippets.

Best,
Mourad

**Comment by nico-bellante** [comment]
I'm having trouble repro-ing this issue on master.
I've tried in Chrome, IE, and Excel Desktop.
@Zlatkovsky have you been able to repro it? Is it possible this bug was already fixed a few weeks ago when we were looking into that deletion problem?

**Comment by Zlatkovsky** [comment]
@maninweb , could you check whether this still repros for you?  We did have an issue around snippet-deletion a couple weeks ago (late April-ish), but we though it's been solved.

In any case, I pushed the latest that we had on master (alpha) and beta to production, so all three environments are the same now.

**Comment by maninweb** [comment]
Hi Michael,
unfortunately, I can still reproduce it in my virtual machine. I uninstalled Script Lab, cleared all things in the IE and reinstalled Script Lab from the store. Below a screenshot about what I have as info for windows, Excel and Script Lab. And another screenshot for the IE, which was installed as is from windows.

![image](https://user-images.githubusercontent.com/13045898/40496587-68b679a8-5f7a-11e8-8dee-c7ce49792fea.png)
![image](https://user-images.githubusercontent.com/13045898/40496851-0b87ebda-5f7b-11e8-8b08-e2e12071dade.png)

I tried both production and alpha mode, I have the same issue. Excel is installed in German.
Best,
Mourad

**Comment by nico-bellante** [comment]
So this is very strange. I am only able to repro this bug if I switch to German.

Also, as a side note, the background color here also seems to be messed up when in German as well.
![image](https://user-images.githubusercontent.com/35939126/40509575-da33510e-5f4e-11e8-97be-7592976f78d0.png)

**Comment by nico-bellante** [comment]
Quite a funny issue that is causing the problem above:

![image](https://user-images.githubusercontent.com/35939126/40510010-2623fbd0-5f50-11e8-967d-590070bf3e75.png)

The css class is being localized. I wonder if this could also be causing the original issue of this thread.

**Comment by nico-bellante** [comment]
After fixing the white bar issue seen above (#825) I am no longer able to reproduce this issue.

**Comment by maninweb** [comment]
Hi nico, thank you :-)

**Comment by nico-bellante** [comment]
No problem :)
